package com.ejemplo.carmenuy.grafica;

import com.ejemplo.carmenuy.grafica.paneles.PanelPresentacion;
import java.awt.BorderLayout;
import javax.accessibility.AccessibleContext;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JRootPane;

public class VentanaJuego extends javax.swing.JFrame {

    /**
     * Creates new form VentanaJuego
     */
    public VentanaJuego() {
        initComponents();
        this.setSize(1000, 800);

        setLayout(new BorderLayout());
        panelBaseJuego.setLayout(new BorderLayout());

//        PanelPresentacion panelPresedntacion = new PanelPresentacion();
//        panelBaseJuego.removeAll();
//        panelBaseJuego.add(panelPresedntacion, BorderLayout.CENTER);
//        panelBaseJuego.revalidate();
//        panelBaseJuego.repaint();
        
        

        // Crear y agregar el panel de presentación
        PanelPresentacion panelPresentacion = new PanelPresentacion();
        panelBaseJuego.removeAll();
        panelBaseJuego.add(panelPresentacion, BorderLayout.CENTER);
        panelBaseJuego.revalidate();
        panelBaseJuego.repaint();

        
        
//        getContentPane().removeAll();
//        getContentPane().add(panelPresedntacion, BorderLayout.CENTER);
//        getContentPane().revalidate();
//        getContentPane().repaint();
        // Configurar BorderLayout para el JFrame, de lo contrario los paneles no se podrán cargar
        this.setVisible(true);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBaseJuego = new javax.swing.JPanel();
        panelBotonesJuego = new javax.swing.JPanel();
        btnCapturarSecuaz = new javax.swing.JButton();
        btnMostrarPista = new javax.swing.JButton();
        btnMoverDetective = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelBaseJuegoLayout = new javax.swing.GroupLayout(panelBaseJuego);
        panelBaseJuego.setLayout(panelBaseJuegoLayout);
        panelBaseJuegoLayout.setHorizontalGroup(
            panelBaseJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelBaseJuegoLayout.setVerticalGroup(
            panelBaseJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );

        btnCapturarSecuaz.setText("CAPTURAR SECUAZ");

        btnMostrarPista.setText("MOSTRAR PISTA");

        btnMoverDetective.setText("MOVER DETECTIVE");

        javax.swing.GroupLayout panelBotonesJuegoLayout = new javax.swing.GroupLayout(panelBotonesJuego);
        panelBotonesJuego.setLayout(panelBotonesJuegoLayout);
        panelBotonesJuegoLayout.setHorizontalGroup(
            panelBotonesJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesJuegoLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnMostrarPista, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnMoverDetective, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnCapturarSecuaz, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        panelBotonesJuegoLayout.setVerticalGroup(
            panelBotonesJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesJuegoLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(panelBotonesJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapturarSecuaz, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMoverDetective, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarPista, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBaseJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelBotonesJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBaseJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelBotonesJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapturarSecuaz;
    private javax.swing.JButton btnMostrarPista;
    private javax.swing.JButton btnMoverDetective;
    private javax.swing.JPanel panelBaseJuego;
    private javax.swing.JPanel panelBotonesJuego;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnCapturarSecuaz() {
        return btnCapturarSecuaz;
    }

    public void setBtnCapturarSecuaz(JButton btnCapturarSecuaz) {
        this.btnCapturarSecuaz = btnCapturarSecuaz;
    }

    public JButton getBtnMostrarPista() {
        return btnMostrarPista;
    }

    public void setBtnMostrarPista(JButton btnMostrarPista) {
        this.btnMostrarPista = btnMostrarPista;
    }

    public JButton getBtnMoverDetective() {
        return btnMoverDetective;
    }

    public void setBtnMoverDetective(JButton btnMoverDetective) {
        this.btnMoverDetective = btnMoverDetective;
    }

    public JPanel getPanelBaseJuego() {
        return panelBaseJuego;
    }

    public void setPanelBaseJuego(JPanel panelBaseJuego) {
        this.panelBaseJuego = panelBaseJuego;
    }

    public JPanel getPanelBotonesJuego() {
        return panelBotonesJuego;
    }

    public void setPanelBotonesJuego(JPanel panelBotonesJuego) {
        this.panelBotonesJuego = panelBotonesJuego;
    }

    public JRootPane getRootPane() {
        return rootPane;
    }

    public void setRootPane(JRootPane rootPane) {
        this.rootPane = rootPane;
    }

    public boolean isRootPaneCheckingEnabled() {
        return rootPaneCheckingEnabled;
    }

    public void setRootPaneCheckingEnabled(boolean rootPaneCheckingEnabled) {
        this.rootPaneCheckingEnabled = rootPaneCheckingEnabled;
    }

    public AccessibleContext getAccessibleContext() {
        return accessibleContext;
    }

    public void setAccessibleContext(AccessibleContext accessibleContext) {
        this.accessibleContext = accessibleContext;
    }

}
